version: "3.9"

volumes:
  - "/home/circleci:/home/circleci"
  - "/etc/passwd:/etc/passwd"
  - "/etc/group:/etc/group"
  
services:
  frontend:
    image: cimg/node:17.2.0
    container_name: mycontainer
    user: "circleci:circleci"
    volumes:
      - type: bind
        source: /etc/passwd
        target: /etc/passwd
        read_only: true
      - type: bind
        source: /etc/group
        target: /etc/group
        read_only: true

    working_dir: /home/circleci/project
    command: yarn install
